apiVersion: apps/v1
kind: Deployment
metadata:
  name: prt-app-deployment
  labels:
    app: prt-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prt-web
  template:
    metadata:
      labels:
        app: prt-web
    spec:
      containers:
      - name: web-app
        image: 281644/prt-web:latest   # Use your Docker image name/tag
        imagePullPolicy: Always 
        ports:
        - containerPort: 80
