apiVersion: apps/v1
kind: Deployment
metadata:
  name: prt-app-deployment
  labels:
    app: prt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prt-app
  template:
    metadata:
      labels:
        app: prt-app
    spec:
      containers:
      - name: prt-app-container
        image: prt-cicd-app:latest   # Use your Docker image name/tag
        ports:
        - containerPort: 80
