apiVersion: v1
kind: Service
metadata:
  name: prt-app-service
spec:
  type: NodePort
  selector:
    app: prt-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080   # Exposes app on <k8s-node-public-ip>:30080
